FROM mcr.microsoft.com/playwright:v1.41.1-jammy

WORKDIR /app

# required by the e2e test code
RUN yarn add "@playwright/test@^1.41.1" "dotenv@^16.3.1"

ENV E2E_BASE_URL="http://localhost:3000"

CMD ["npx", "playwright", "test", "-c", "e2e/config/playwright.config.ci.ts"]