services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.0}
    ports:
      - ${GRAFANA_PORT:-3000}:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
      - ./samples/provisioning-local:/etc/grafana/provisioning
      - ./samples/dashboards:/var/lib/grafana/dashboards
    environment:
    # prevents a Grafana startup error in case a newer plugin version (set in package.json) is used compared to the latest one published in the catalog
      GF_PLUGINS_PREINSTALL_DISABLED: true
      GF_INSTALL_PLUGINS: grafana-llm-app
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_ORGANIZATION_ID: $OPENAI_ORGANIZATION_ID

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-storage:/qdrant/storage

  rideshare:
    build:
      context: ./samples/rideshare
    ports:
      - 5000
    environment:
      - PYROSCOPE_SERVER_ADDRESS=http://host.docker.internal:4040
      # Set this to 1 to turn on debug logging.
      - DEBUG=0
    deploy:
      mode: replicated
      replicas: 5

  rideshare-load-generator:
    build:
      context: ./samples/rideshare
      dockerfile: Dockerfile.load-generator
    environment:
      - HOST_PREFIX=pyroscope-app-plugin-rideshare
      # This should be the same as the rideshare replica count.
      - REPLICAS=5
      # Set this to 1 to turn on debug logging.
      - DEBUG=0
    depends_on:
      - rideshare
    logging:
      driver: none

volumes:
  qdrant-storage:
