services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      dockerfile: ./Dockerfile.remote
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.0}
        backendUrl: ${REMOTE_BACKEND_URL}
        basicAuthUser: ${REMOTE_BASIC_AUTH_USER}
        basicAuthPassword: ${REMOTE_BASIC_AUTH_PASSWORD}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
      # TODO(simonswine): DO NOT MERGE, this should be a regular app dependency instaed, but first https://github.com/grafana/grafana-collector-app/pull/639 needs to merge.
      - ../grafana-collector-app/dist:/var/lib/grafana/plugins/grafana-collector-app

    environment:
      GF_INSTALL_PLUGINS: grafana-llm-app
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_ORGANIZATION_ID: $OPENAI_ORGANIZATION_ID
      AGM_API_KEY: $AGM_API_KEY
      FLEET_API_KEY: $FLEET_API_KEY

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
