FROM alpine:latest@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS blocks

COPY samples/static/grafana-pyroscope-sample-blocks-public.zip /

RUN unzip grafana-pyroscope-sample-blocks-public.zip \
 && mv grafana-pyroscope-sample-blocks-public data-shared \
 && rm grafana-pyroscope-sample-blocks-public.zip

FROM docker.io/grafana/pyroscope:weekly-f129-6d0f4264a@sha256:89f1108d5534e3de0a54d72e4eb36c11d300a16029b1bc289886694ef307349a

COPY samples/static/pyroscope/config.yaml /etc/pyroscope/config.yaml
COPY --from=blocks --chown=pyroscope:pyroscope data-shared /data-shared

ENTRYPOINT ["/usr/bin/pyroscope"]
CMD ["-config.file=/etc/pyroscope/config.yaml"]
