services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.0}
    ports:
      - ${GRAFANA_PORT:-3000}:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
      - ./samples/provisioning:/etc/grafana/provisioning
      - ./samples/dashboards:/var/lib/grafana/dashboards
    environment:
      # prevents a Grafana startup error in case a newer plugin version (set in package.json) is used compared to the latest one published in the catalog
      GF_PLUGINS_PREINSTALL_DISABLED: true
      GF_INSTALL_PLUGINS: grafana-llm-app
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_ORGANIZATION_ID: $OPENAI_ORGANIZATION_ID
      GF_FEATURE_TOGGLES_ENABLE: metricsFromProfiles

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-storage:/qdrant/storage

  pyroscope:
    container_name: 'pyroscope-static-e2e'
    build:
      dockerfile: ./Dockerfile.pyroscope.e2e
      context: .
    ports:
      - 4100:4100/tcp
    environment:
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      GITHUB_SESSION_SECRET: $GITHUB_SESSION_SECRET

volumes:
  qdrant-storage:
