ARG grafana_image=grafana-enterprise
ARG grafana_version=latest@sha256:0fa9cbdd2826d3866238a22f12330aa70f263129324509756fe0ee1b570a8e21

FROM grafana/${grafana_image}:${grafana_version}

ARG backendUrl
ARG basicAuthUser
ARG basicAuthPassword

# Make it as simple as possible to access the grafana instance for development purposes
# Do NOT enable these settings in a public facing / production grafana instance
ENV GF_AUTH_ANONYMOUS_ORG_ROLE="Admin"
ENV GF_AUTH_ANONYMOUS_ENABLED="true"
ENV GF_AUTH_BASIC_ENABLED="false"
# Set development mode so plugins can be loaded without the need to sign
ENV GF_DEFAULT_APP_MODE="development"

# Credentials for fecthing remote profile data
ENV REMOTE_BACKEND_URL=$backendUrl
ENV REMOTE_BASIC_AUTH_USER=$basicAuthUser
ENV REMOTE_BASIC_AUTH_PASSWORD=$basicAuthPassword

USER root

# This ensures that the basicAuthUser value is a string and not a number
# which would make the requests to the backend fail
COPY ./samples/provisioning-remote/plugins/app.yaml  /etc/grafana/provisioning/plugins
RUN sed -i "s/\$REMOTE_BASIC_AUTH_USER/'$REMOTE_BASIC_AUTH_USER'/g" /etc/grafana/provisioning/plugins/app.yaml

COPY ./samples/provisioning-remote/datasources/datasources.yaml  /etc/grafana/provisioning/datasources
RUN sed -i "s/\$REMOTE_BASIC_AUTH_USER/'$REMOTE_BASIC_AUTH_USER'/g" /etc/grafana/provisioning/datasources/datasources.yaml

