FROM aleksandarxpetrov/pyroscope:feat-ad-hoc-component-6913c0991

USER root

COPY samples/static/pyroscope/* /etc/pyroscope

COPY samples/static/grafana-pyroscope-sample-blocks-public.zip /
RUN unzip grafana-pyroscope-sample-blocks-public.zip 
RUN mv grafana-pyroscope-sample-blocks-public data-shared
RUN rm grafana-pyroscope-sample-blocks-public.zip

ENTRYPOINT ["/usr/bin/pyroscope"]
CMD ["-config.file=/etc/pyroscope/config.yaml"]
