FROM mcr.microsoft.com/playwright:v1.56.1@sha256:f1e7e01021efd65dd1a2c56064be399f3e4de00fd021ac561325f2bfbb2b837a

WORKDIR /app

# required by the e2e test code
RUN yarn add "@playwright/test@^1.56.0" "dotenv@^16.3.1"

ENV E2E_BASE_URL="http://localhost:3000"

ENV TZ=Europe/Madrid

ENTRYPOINT ["npx", "playwright", "test", "-c", "e2e/config/playwright.config.ci.ts"]
