version: '3.0'

services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.1.1}
    ports:
      - ${GRAFANA_PORT:-3000}:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
      - ./samples/provisioning:/etc/grafana/provisioning
      - ./samples/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_INSTALL_PLUGINS: grafana-llm-app
      OPENAI_API_KEY: $OPENAI_API_KEY

  pyroscope:
    container_name: 'pyroscope-static'
    build:
      dockerfile: ./Dockerfile.static
      context: .
    ports:
      - 4100:4100/tcp

  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
