version: '3.0'

services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.1.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
      - ./provisioning:/etc/grafana/provisioning
  phlare:
    image: grafana/phlare:weekly-f23-806280da
    ports:
      - 4100:4100/tcp
    logging:
      driver: none

  go-agent:
    build:
      context: ./hacks/golang-simple
    environment:
      - PYROSCOPE_SERVER_ADDRESS=http://phlare:4100
    logging:
      driver: none
