version: '3.0'

services:
  grafana:
    container_name: 'grafana-pyroscope-app'
    build:
      dockerfile: ./Dockerfile.remote
      args:
        grafana_version: ${GRAFANA_VERSION:-10.1.1}
        backendUrl: ${REMOTE_BACKEND_URL}
        basicAuthUser: ${REMOTE_BASIC_AUTH_USER}
        basicAuthPassword: ${REMOTE_BASIC_AUTH_PASSWORD}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-pyroscope-app
    environment:
      GF_INSTALL_PLUGINS: grafana-llm-app
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_ORGANIZATION_ID: $OPENAI_ORGANIZATION_ID
