FROM alpine:latest AS blocks

COPY samples/static/grafana-pyroscope-sample-blocks-public.zip /

RUN unzip grafana-pyroscope-sample-blocks-public.zip \
 && mv grafana-pyroscope-sample-blocks-public data-shared \
 && rm grafana-pyroscope-sample-blocks-public.zip

FROM docker.io/grafana/pyroscope:weekly-f129-6d0f4264a

COPY samples/static/pyroscope/config.yaml /etc/pyroscope/config.yaml
COPY --from=blocks --chown=pyroscope:pyroscope data-shared /data-shared

ENTRYPOINT ["/usr/bin/pyroscope"]
CMD ["-config.file=/etc/pyroscope/config.yaml"]
