import { usePluginContext } from '@grafana/data';
import { Icon, Toggletip } from '@grafana/ui';
import React, { useMemo } from 'react';

// Extract version information from the package.json files
// The consequences of importing them into the source code are that the contents of these package files will be in the built result
// The pyroscope package file is publically available in open source, the plugin package file is not, but on the most part it resembles
// the boilerplate generated by Grafana's plugin scaffolding.
import pkg from '../../../package.json';
import { GIT_COMMIT } from '../../version';

const pluginCommitSha = GIT_COMMIT;
const pluginCommitURL = `https://github.com/grafana/pyroscope-app-plugin/commit/${pluginCommitSha}`;
const pyroscopeGitInfo = pkg.dependencies['grafana-pyroscope'];
const pyroscopeCommitSha = pyroscopeGitInfo.split('#')[1];
const pyroscopeCommitURL = `https://github.com/grafana/pyroscope/commit/${pyroscopeCommitSha}`;

export function VersionInfoTooltip() {
  const {
    meta: {
      info: { version, updated },
    },
  } = usePluginContext();

  const versionInfo = useMemo(() => {
    const lastUpdate = new Date(updated).toLocaleString();

    return (
      <dl>
        <dt>Plugin version</dt>
        <dd>{version}</dd>
        <dt>Last update</dt>
        <dd>{lastUpdate}</dd>
        <dt>Commit SHA</dt>
        <dd>
          {' '}
          <a href={pluginCommitURL} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'underline' }}>
            {pluginCommitSha}
          </a>
        </dd>
        <dt>Pyroscope commit SHA</dt>
        <dd>
          {' '}
          <a
            href={pyroscopeCommitURL}
            target="_blank"
            rel="noopener noreferrer"
            style={{ textDecoration: 'underline' }}
          >
            {pyroscopeCommitSha}
          </a>
        </dd>
      </dl>
    );
  }, [version, updated]);

  return (
    <Toggletip content={versionInfo} theme="info" placement="top-start">
      <Icon name="info-circle" />
    </Toggletip>
  );
}
