import { css } from '@emotion/css';
import { GrafanaTheme2, usePluginContext } from '@grafana/data';
import { config } from '@grafana/runtime';
import { Icon, Toggletip, useStyles2 } from '@grafana/ui';
import React, { useMemo } from 'react';

// Extract version information from the package.json files
// The consequences of importing them into the source code are that the contents of these package files will be in the built result
// The pyroscope package file is publically available in open source, the plugin package file is not, but on the most part it resembles
// the boilerplate generated by Grafana's plugin scaffolding.
import pkg from '../../../package.json';
import { GIT_COMMIT } from '../../version';

const pluginCommitSha = GIT_COMMIT;
const pluginCommitURL = `https://github.com/grafana/pyroscope-app-plugin/commit/${pluginCommitSha}`;
const pyroscopeGitInfo = pkg.dependencies['grafana-pyroscope'];
const pyroscopeCommitSha = pyroscopeGitInfo.split('#')[1];
const pyroscopeCommitURL = `https://github.com/grafana/pyroscope/commit/${pyroscopeCommitSha}`;

const { buildInfo } = config;

const grafanaCommitURL = `https://github.com/grafana/grafana/commit/${buildInfo.commit}`;

const getStyles = (theme: GrafanaTheme2) => ({
  term: css`
    color: ${theme.colors.text.maxContrast};
    text-transform: uppercase;
  `,
});

export function VersionInfoTooltip() {
  const styles = useStyles2(getStyles);
  const {
    meta: {
      info: { version, updated },
    },
  } = usePluginContext();

  const versionInfo = useMemo(() => {
    const lastUpdate = new Date(updated).toLocaleString();

    return (
      <dl>
        <dt className={styles.term}>Grafana {buildInfo.edition}</dt>
        <dd>
          🔗{' '}
          <a href={grafanaCommitURL} target="_blank" rel="noopener noreferrer" title="Go to commit">
            v{buildInfo.version}
          </a>
        </dd>
        <dt className={styles.term}>Environment</dt>
        <dd>{buildInfo.env}</dd>
        <dt className={styles.term}>Plugin version</dt>
        <dd>{version}</dd>
        <dt className={styles.term}>Last update</dt>
        <dd>{lastUpdate}</dd>
        <dt className={styles.term}>Commit SHA</dt>
        <dd>
          🔗{' '}
          <a href={pluginCommitURL} target="_blank" rel="noopener noreferrer" title="Go to commit">
            {pluginCommitSha}
          </a>
        </dd>
        <dt className={styles.term}>Pyroscope Commit SHA</dt>
        <dd>
          🔗{' '}
          <a href={pyroscopeCommitURL} target="_blank" rel="noopener noreferrer" title="Go to commit">
            {pyroscopeCommitSha}
          </a>
        </dd>
      </dl>
    );
  }, [updated, styles.term, version]);

  return (
    <Toggletip content={versionInfo} theme="info" placement="top-start">
      <Icon name="info-circle" />
    </Toggletip>
  );
}
