// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file settings/v1/collection_rules.proto (package settings.v1, syntax proto3)
/* eslint-disable */

import { CollectionRulesService } from "./collection_rules_pb";

/**
 * @generated from rpc settings.v1.CollectionRulesService.GetCollectionRule
 */
export const getCollectionRule = CollectionRulesService.method.getCollectionRule;

/**
 * @generated from rpc settings.v1.CollectionRulesService.UpsertCollectionRule
 */
export const upsertCollectionRule = CollectionRulesService.method.upsertCollectionRule;

/**
 * @generated from rpc settings.v1.CollectionRulesService.ListCollectionRules
 */
export const listCollectionRules = CollectionRulesService.method.listCollectionRules;

/**
 * @generated from rpc settings.v1.CollectionRulesService.DeleteCollectionRule
 */
export const deleteCollectionRule = CollectionRulesService.method.deleteCollectionRule;
