// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file settings/v1/setting.proto (package settings.v1, syntax proto3)
/* eslint-disable */

import { SettingsService } from "./setting_pb";

/**
 * @generated from rpc settings.v1.SettingsService.Get
 */
export const get = SettingsService.method.get;

/**
 * @generated from rpc settings.v1.SettingsService.Set
 */
export const set = SettingsService.method.set;

/**
 * @generated from rpc settings.v1.SettingsService.Delete
 */
export const delete$ = SettingsService.method.delete;
