// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file settings/v1/setting.proto (package settings.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file settings/v1/setting.proto.
 */
export const file_settings_v1_setting: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXR0aW5ncy92MS9zZXR0aW5nLnByb3RvEgtzZXR0aW5ncy52MSIUChJHZXRTZXR0aW5nc1JlcXVlc3QiPQoTR2V0U2V0dGluZ3NSZXNwb25zZRImCghzZXR0aW5ncxgBIAMoCzIULnNldHRpbmdzLnYxLlNldHRpbmciOwoSU2V0U2V0dGluZ3NSZXF1ZXN0EiUKB3NldHRpbmcYASABKAsyFC5zZXR0aW5ncy52MS5TZXR0aW5nIjwKE1NldFNldHRpbmdzUmVzcG9uc2USJQoHc2V0dGluZxgBIAEoCzIULnNldHRpbmdzLnYxLlNldHRpbmciJQoVRGVsZXRlU2V0dGluZ3NSZXF1ZXN0EgwKBG5hbWUYASABKAkiGAoWRGVsZXRlU2V0dGluZ3NSZXNwb25zZSI6CgdTZXR0aW5nEgwKBG5hbWUYASABKAkSDQoFdmFsdWUYAiABKAkSEgoKbW9kaWZpZWRBdBgDIAEoAzL+AQoPU2V0dGluZ3NTZXJ2aWNlEkoKA0dldBIfLnNldHRpbmdzLnYxLkdldFNldHRpbmdzUmVxdWVzdBogLnNldHRpbmdzLnYxLkdldFNldHRpbmdzUmVzcG9uc2UiABJKCgNTZXQSHy5zZXR0aW5ncy52MS5TZXRTZXR0aW5nc1JlcXVlc3QaIC5zZXR0aW5ncy52MS5TZXRTZXR0aW5nc1Jlc3BvbnNlIgASUwoGRGVsZXRlEiIuc2V0dGluZ3MudjEuRGVsZXRlU2V0dGluZ3NSZXF1ZXN0GiMuc2V0dGluZ3MudjEuRGVsZXRlU2V0dGluZ3NSZXNwb25zZSIAYgZwcm90bzM");

/**
 * @generated from message settings.v1.GetSettingsRequest
 */
export type GetSettingsRequest = Message<"settings.v1.GetSettingsRequest"> & {
};

/**
 * Describes the message settings.v1.GetSettingsRequest.
 * Use `create(GetSettingsRequestSchema)` to create a new message.
 */
export const GetSettingsRequestSchema: GenMessage<GetSettingsRequest> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 0);

/**
 * @generated from message settings.v1.GetSettingsResponse
 */
export type GetSettingsResponse = Message<"settings.v1.GetSettingsResponse"> & {
  /**
   * @generated from field: repeated settings.v1.Setting settings = 1;
   */
  settings: Setting[];
};

/**
 * Describes the message settings.v1.GetSettingsResponse.
 * Use `create(GetSettingsResponseSchema)` to create a new message.
 */
export const GetSettingsResponseSchema: GenMessage<GetSettingsResponse> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 1);

/**
 * @generated from message settings.v1.SetSettingsRequest
 */
export type SetSettingsRequest = Message<"settings.v1.SetSettingsRequest"> & {
  /**
   * @generated from field: settings.v1.Setting setting = 1;
   */
  setting?: Setting;
};

/**
 * Describes the message settings.v1.SetSettingsRequest.
 * Use `create(SetSettingsRequestSchema)` to create a new message.
 */
export const SetSettingsRequestSchema: GenMessage<SetSettingsRequest> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 2);

/**
 * @generated from message settings.v1.SetSettingsResponse
 */
export type SetSettingsResponse = Message<"settings.v1.SetSettingsResponse"> & {
  /**
   * @generated from field: settings.v1.Setting setting = 1;
   */
  setting?: Setting;
};

/**
 * Describes the message settings.v1.SetSettingsResponse.
 * Use `create(SetSettingsResponseSchema)` to create a new message.
 */
export const SetSettingsResponseSchema: GenMessage<SetSettingsResponse> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 3);

/**
 * @generated from message settings.v1.DeleteSettingsRequest
 */
export type DeleteSettingsRequest = Message<"settings.v1.DeleteSettingsRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message settings.v1.DeleteSettingsRequest.
 * Use `create(DeleteSettingsRequestSchema)` to create a new message.
 */
export const DeleteSettingsRequestSchema: GenMessage<DeleteSettingsRequest> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 4);

/**
 * @generated from message settings.v1.DeleteSettingsResponse
 */
export type DeleteSettingsResponse = Message<"settings.v1.DeleteSettingsResponse"> & {
};

/**
 * Describes the message settings.v1.DeleteSettingsResponse.
 * Use `create(DeleteSettingsResponseSchema)` to create a new message.
 */
export const DeleteSettingsResponseSchema: GenMessage<DeleteSettingsResponse> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 5);

/**
 * @generated from message settings.v1.Setting
 */
export type Setting = Message<"settings.v1.Setting"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  /**
   * @generated from field: int64 modifiedAt = 3;
   */
  modifiedAt: bigint;
};

/**
 * Describes the message settings.v1.Setting.
 * Use `create(SettingSchema)` to create a new message.
 */
export const SettingSchema: GenMessage<Setting> = /*@__PURE__*/
  messageDesc(file_settings_v1_setting, 6);

/**
 * @generated from service settings.v1.SettingsService
 */
export const SettingsService: GenService<{
  /**
   * @generated from rpc settings.v1.SettingsService.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetSettingsRequestSchema;
    output: typeof GetSettingsResponseSchema;
  },
  /**
   * @generated from rpc settings.v1.SettingsService.Set
   */
  set: {
    methodKind: "unary";
    input: typeof SetSettingsRequestSchema;
    output: typeof SetSettingsResponseSchema;
  },
  /**
   * @generated from rpc settings.v1.SettingsService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteSettingsRequestSchema;
    output: typeof DeleteSettingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_settings_v1_setting, 0);

