// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file adhocprofiles/v1/adhocprofiles.proto (package adhocprofiles.v1, syntax proto3)
/* eslint-disable */

import { AdHocProfileService } from "./adhocprofiles_pb";

/**
 * Upload a profile to the underlying store. The request contains a name and a base64 encoded pprof file. The response
 * contains a generated unique identifier, a flamegraph and a list of found sample types within the profile.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.Upload
 */
export const upload = AdHocProfileService.method.upload;

/**
 * Retrieves a profile from the underlying store by id and an optional sample type. The response is similar to the one
 * for the upload method.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.Get
 */
export const get = AdHocProfileService.method.get;

/**
 * Retrieves a list of profiles found in the underlying store.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.List
 */
export const list = AdHocProfileService.method.list;
