#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

mkdir -p ./gpx_files
mv ./dist/gpx_* ./gpx_files

DRONE_BUILD_NUMBER=$1

# if we ever need to build for multiple platforms, we can use this array (plus don't forget to adjust the mv command below):
# platforms=("darwin_amd64" "darwin_arm64" "linux_amd64" "linux_arm" "linux_arm64" "windows_amd64.exe")

platforms=("linux_amd64")

for platform in "${platforms[@]}"; do
  # mv "gpx_files/gpx_pyroscope_app_${platform}" ./dist
  yarn sign
  ls -1 ./dist

  # Have to move the dist directory, otherwise when we submit plugin we get this error:
  # > Archive root directory named dist. It should contain a directory named grafana-pyroscope-app
  mv dist grafana-pyroscope-app
  if [[ $platform == *.exe ]]; then
    # Adjust zip file name for the Windows .exe file
    zip -r "grafana-pyroscope-app-$DRONE_BUILD_NUMBER-windows_amd64.zip" ./grafana-pyroscope-app
  else
    zip -r "grafana-pyroscope-app-$DRONE_BUILD_NUMBER-${platform}.zip" ./grafana-pyroscope-app
  fi
  mv grafana-pyroscope-app dist

  rm "dist/gpx_pyroscope_app_${platform}"
done

# for compatibility with the old naming scheme
cp "grafana-pyroscope-app-$DRONE_BUILD_NUMBER-linux_amd64.zip" "grafana-pyroscope-app-$DRONE_BUILD_NUMBER.zip"

ls -lah grafana-pyroscope-app-*.zip
