#!/usr/bin/env bash
VERSION=$(git describe --dirty --tags --always --abbrev=10 --exclude 'grafana-pyroscope-app/*')

generate_version_env() {
    local dirs="${*:?}"
    declare -A BUILD
    BUILD[COMMIT]=$(git rev-parse 'HEAD^{commit}')
    BUILD[BRANCH]=$(git rev-parse --abbrev-ref HEAD)
    BUILD[STAMP]=$(date --utc --rfc-3339=seconds)
    BUILD[VERSION]="${VERSION}"
    # Build VERSION_ENV multi-line string with BUILD[] associative array content, as:
    #  BUILD_COMMIT=${BUILD[COMMIT]}
    #  BUILD_BRANCH=${BUILD[BRANCH]}
    VERSION_ENV=$(for k in "${!BUILD[@]}"; do echo "export BUILD_${k}=${BUILD[$k]}";done)
    for dir in ${dirs:?}; do
        echo "${VERSION_ENV}" > ${dir}/version.env
    done
}

case "$1" in
    --env) shift; generate_version_env "${@}"; exit $?;;
esac
echo "${VERSION}"
