name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: coverage

      - name: Build backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-build
          path: dist
          retention-days: 1

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [backend]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # lint
      - name: Check TS types
        run: yarn typecheck
      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test:ci

      # before the frontend build so that the folder is not overwritten
      - name: Download backend build
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: dist

      - name: Make backend build executable
        run: chmod +x dist/gpx_pyroscope_app_*

      - name: Build frontend
        run: yarn build

      # e2e test
      - name: Start Grafana server
        run: yarn e2e:ci:server:up

      # commented to save time during the build (building this action takes ~30s)
      # the next step "Prepare e2e test" takes ~20s, which gives us the time needed
      # uncomment it if you experience flakiness
      # - uses: cygnetdigital/wait_for_response@v2.0.0
      #   with:
      #     url: 'http://localhost:3000/a/grafana-pyroscope-app/single'
      #     responseCode: '200'
      #     timeout: 20000
      #     interval: 500

      # we do this here to give a bit more time to the app to start
      - name: Prepare e2e tests
        run: yarn e2e:prepare

      - name: Run e2e tests
        run: yarn e2e:ci

      - name: Stop Grafana server
        run: yarn e2e:ci:server:down

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-reports-and-results
          path: |
            e2e/test-reports
            e2e/test-results
          retention-days: 15
