# trigger zizmor
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/*
      - docs/sources/**
    branches:
      - main

env:
  BUNDLEWATCH_GITHUB_TOKEN: ${{secrets.BUNDLEWATCH_GITHUB_TOKEN}}

jobs:
  build:
    name: Build and test
    permissions:
      contents: read
      pull-requests: write # required to create PR comment with test coverage
      id-token: read
    if: github.actor != 'databases-frontend-ci-bot[bot]'
    uses: ./.github/workflows/build.yml
    with:
      e2e: true
      addSha: true

  upload-sha:
    name: Upload sha commit tag to GCS
    # Required to create OIDC/JWT token required to use shared actions
    permissions:
      contents: read
      id-token: write
    needs: [build]
    # Make uploads available only from main (needed for deployments)
    if: github.event_name == 'push'
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      github_environment: gcs-no-approval

  upload-edge:
    name: Upload edge tag to GCS
    # Required to create OIDC/JWT token required to use shared actions
    permissions:
      contents: read
      id-token: write
    needs: [build]
    # Make uploads available only from main (needed for deployments)
    if: github.event_name == 'push'
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: 'edge'
      github_environment: gcs-no-approval

  upload-main:
    name: Upload main tag to GCS
    # Required to create OIDC/JWT token required to use shared actions
    permissions:
      contents: read
      id-token: write
    needs: [build]
    # Make uploads available only from main (needed for deployments)
    if: github.event_name == 'push'
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: 'main'
      github_environment: gcs-no-approval

  deploy-main-to-dev-and-ops:
    name: Deploy
    # Required to create OIDC/JWT token required to use shared actions
    permissions:
      contents: read
      id-token: write
    needs: [upload-sha, upload-edge, upload-main]
    uses: ./.github/workflows/deploy.yml
    # Make deployments available only from main
    if: github.event_name == 'push'
    secrets: inherit
    strategy:
      matrix:
        environment: [dev, ops]
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      environment: ${{ matrix.environment }}
