name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  CI:
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v7.0.0
    with:
      run-playwright: false
      run-playwright-docker: true
      run-playwright-with-skip-grafana-dev-image: true
      upload-playwright-artifacts: true
      run-playwright-with-grafana-dependency: '>=12.2.5'
      playwright-config: e2e/config/playwright.config.ci.ts
      playwright-docker-compose-file: docker-compose.e2e.yaml
      playwright-report-path: e2e/test-reports/
