name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/*
      - docs/sources/**
    branches:
      - main

env:
  BUNDLEWATCH_GITHUB_TOKEN: ${{secrets.BUNDLEWATCH_GITHUB_TOKEN}}

# Required to create OIDC/JWT token required to use shared actions
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}

  package:
    needs: [build]
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      github_environment: ${{ github.event_name != 'push' && 'gcs' || 'gcs-no-approval' }}

  deploy-main-to-dev-and-ops:
    name: Deploy to dev / ops
    needs: [package]
    uses: grafana/explore-profiles/.github/workflows/deploy.yml
    # Make
    if: github.event_name == 'push'
    secrets: inherit
    strategy:
      matrix:
        environment: [dev, ops]
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      environment: ${{ matrix.environment }}
