name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/*
      - docs/sources/**
    branches:
      - main

env:
  BUNDLEWATCH_GITHUB_TOKEN: ${{secrets.BUNDLEWATCH_GITHUB_TOKEN}}

# Required to create OIDC/JWT token required to use shared actions
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: grafana/explore-profiles/.github/workflows/build.yml@ifrost/manual-release-workflow
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}

  package:
    needs: [build]
    environment: ${{ github.event_name != 'push' && 'gcs' || 'gcs-no-approval' }}
    uses: grafana/explore-profiles/.github/workflows/package.yml@ifrost/manual-release-workflow
    secrets: inherit
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}

  deploy:
    needs: [package]
    environment: dev
    uses: grafana/explore-profiles/.github/workflows/deploy.yml@ifrost/manual-release-workflow
    secrets: inherit
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      environment: dev
