name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/*
      - docs/sources/**
    branches:
      - main

env:
  BUNDLEWATCH_GITHUB_TOKEN: ${{secrets.BUNDLEWATCH_GITHUB_TOKEN}}

# Required to create OIDC/JWT token required to use shared actions
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build and test
    if: github.actor != 'databases-frontend-ci-bot[bot]'
    uses: ./.github/workflows/build.yml
    with:
      e2e: true

  upload:
    name: Upload
    needs: [build]
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      github_environment: ${{ github.event_name != 'push' && 'gcs' || 'gcs-no-approval' }}

  deploy-main-to-dev-and-ops:
    name: Deploy
    needs: [upload]
    uses: ./.github/workflows/deploy.yml
    # Make deployments available only from main
    if: github.event_name == 'push'
    secrets: inherit
    strategy:
      matrix:
        environment: [dev, ops]
    with:
      version: ${{ github.event.pull_request.head.sha || github.sha }}
      environment: ${{ matrix.environment }}
