name: Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
        description: dev, ops or prod

jobs:
  deploy-to-cloud:
    # This triggers Argo workflow that will perform deployment to wave. Pushes to main will trigger deployment automatically
    name: Deploy to ${{ inputs.environment }} wave
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ${{ inputs.version }} to ${{ inputs.environment }}
        uses: grafana/shared-workflows/actions/trigger-argo-workflow@trigger-argo-workflow-v1.1.0
        with:
          instance: 'ops'
          namespace: 'phlare-cd'
          workflow_template: 'deploy-plugin-${{ inputs.environment }}'
          parameters: |
            plugintag=${{ inputs.version }}
          extra_args: '--name deploy-plugin-${{ inputs.environment }}-${{ inputs.version }}-${{ github.run_id }}-${{ github.run_attempt }}'
          log_level: 'debug'
