name: Crowdin automatic task management

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  create-tasks-in-crowdin:
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Get vault secrets'
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@f1614b210386ac420af6807a997ac7f6d96e477a # get-vault-secrets/v1.3.1 (2026-02-19)
        with:
            # Vault secret paths:
            # - ci/repo/grafana/profiles-drilldown/grafana-frontend-crowdin-token
            repo_secrets: |
                CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Create tasks in Crowdin
        uses: grafana/grafana-github-actions/crowdin-create-tasks@3c62d35c5a66e730186a338e45aeb8fa784e2d56 # commit 3c62d35 (no release tag, 2026-05-21)
        with:
          crowdin_token: ${{ env.CROWDIN_TOKEN }}
          crowdin_project_id: 42
