name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download-sources-from-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-download.yml@ea6ae56f0c8cee10e6538c6e395f5dc1072bf3a2 # main
    with:
      crowdin_project_id: 42
      pr_labels: "i18n"
      github_board_id: 42
