name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - "src/locales/en-US/grafana-pyroscope-app.json"
    branches:
      - main

jobs:
  upload-sources-to-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-upload.yml@ea6ae56f0c8cee10e6538c6e395f5dc1072bf3a2 # main
    with:
      crowdin_project_id: 42
