name: Verify i18n markup has been committed

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-i18n:
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@ea6ae56f0c8cee10e6538c6e395f5dc1072bf3a2 # main
