name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  check-title:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 (2026-01-09)
        with:
          persist-credentials: false
      - uses: grafana/shared-workflows/actions/lint-pr-title@0239db2665246f3b078d8d9166e4d8f09c071cae # lint-pr-title/v1.2.2 (2026-05-04)
        with:
          config-path: ${{ github.workspace }}/.github/commitlint.config.js
        env:
          GITHUB_TOKEN: ${{ github.token }}
