name: 'PR Conventional Commit Validation'

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@b7be9213c4fa33260646db6c9b905332dc90b310 # 1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","build"]'
          add_label: 'true'
          custom_labels: '{"docs": "type/docs"}'
