name: publish-technical-documentation-next

on:
  push:
    branches:
      - main
    paths:
      - 'docs/sources/**'
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/profiles-drilldown'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: grafana/writers-toolkit/publish-technical-documentation@publish-technical-documentation/v1
        with:
          website_directory: content/docs/explore-profiles/next
