# trigger zizmor
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 6 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          # Number of days of inactivity before a stale Issue or Pull Request is closed.
          # Set to -1 to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
          days-before-close: 14
          # Number of days of inactivity before an Issue or Pull Request becomes stale
          days-before-stale: 90
          exempt-issue-labels: no stalebot,planned
          exempt-pr-labels: no stalebot,planned
          operations-per-run: 100
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity in the last 90 days. It will be closed in 2 weeks if no further activity occurs.
          close-issue-message: >
            This issue has been automatically closed because it has not had activity in the last 2 weeks.
          stale-pr-label: stale
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            activity in the last 90 days. It will be closed in 2 weeks if no further activity occurs. Please
            feel free to give a status update now, ping for review, or re-open when it's ready.
            Thank you for your contributions!
          close-pr-message: >
            This pull request has been automatically closed because it has not had
            activity in the last 2 weeks. Please feel free to give a status update now, ping for review, or re-open when it's ready.
            Thank you for your contributions!
