on:
  workflow_call:
    inputs:
      test:
        type: string

jobs:
  test:
    name: Job test = ${{ inputs.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Step test = ${{ inputs.test }}
        run: echo test = ${{ inputs.test }}
