name: Update `make docs` procedure
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
jobs:
  main:
    if: github.repository == 'grafana/profiles-drilldown'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/writers-toolkit/update-make-docs@update-make-docs/v1
        with:
          pr_options: >
            --title 'chore(docs): Update `make docs` to latest version'
