name: weekly-release

on:
  push:
    branches:
      - 'weekly/f*'
jobs:
  weekly-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set WEEKLY_IMAGE_TAG
        run: echo "WEEKLY_IMAGE_TAG=$(./scripts/image-tag)" >> $GITHUB_ENV
      - run: git fetch --force --tags
      - name: Create tags for this weekly release
        run: |
          git tag "$WEEKLY_IMAGE_TAG"
      - name: Push git tag for weekly release
        run: git push origin "${WEEKLY_IMAGE_TAG}"
